apiVersion: v1
kind: Service
metadata:
  name: counter-service
spec:
  # Ip externo, acessível fora do cluster
  type: NodePort
  selector:
    # todo Pod que tiver essa tag
    # fará parte desse serviço
    app: counter
  ports:
    - name: counter
      protocol: TCP
      # o nó recebe requisições nessa porta
      port: 7000
      # e direciona para essa porta do Pod
      targetPort: 7000
      nodePort: 30007