#deployments vem de apps/v1
apiVersion: apps/v1
#tipo
kind: Deployment
metadata:
  #nome do deployment
  name: query-deployment
spec:
  #quantas cópias
  replicas: 1
  #para especificar o rótulo
  selector:
    matchLabels:
    #rótulo, app não tem nada de especial, pode ser qq coisa
    #Deployment vai selecionar todo Pod que tiver esse rótulo
      app: query
  #modelo que vai ser usado para construção dos Pods
  template:
    metadata:
      labels:
        #os Pods terão esse rótulo, assim,
        #serão selecionados por esse deployment
        app: query
    spec:
      containers:
        - name: query
          image: query-image
          imagePullPolicy: Never
          resources:
            limits:
              memory: 256Mi
              cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  #nome diferente do outro de tipo nodePort
  #que havíamos criado
  name: query-clusterip-service
spec:
  selector:
    app: query
  ports:
    - name: query
      protocol: TCP
      port: 8000
      targetPort: 8000