apiVersion: v1
kind: Service
metadata:
  name: query-service
spec:
  # Ip externo, acessível fora do cluster
  type: NodePort
  selector:
    # todo Pod que tiver essa tag
    # fará parte desse serviço
    app: query
  ports:
    - name: query
      protocol: TCP
      # o nó recebe requisições nessa porta
      port: 8000
      # e direciona para essa porta do Pod
      targetPort: 8000
      nodePort: 30008