apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  # Ip externo, acessível fora do cluster
  type: NodePort
  selector:
    # todo Pod que tiver essa tag
    # fará parte desse serviço
    app: react
  ports:
    - name: react
      protocol: TCP
      # o nó recebe requisições nessa porta
      port: 5173
      # e direciona para essa porta do Pod
      targetPort: 5173
      nodePort: 30011