apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  # Ip externo, acessível fora do cluster
  type: NodePort
  selector:
    # todo Pod que tiver essa tag
    # fará parte desse serviço
    app: user
  ports:
    - name: user
      protocol: TCP
      # o nó recebe requisições nessa porta
      port: 3000
      # e direciona para essa porta do Pod
      targetPort: 3000
      nodePort: 30003